package chat

// EmptyParameters is an empty parameter object used for a Function that accepts no arguments.
var EmptyParameters = Schema{
	Type:       "object",
	Properties: map[string]Schema{},
}

const (
	// FunctionCallAuto indicates the model should decide whether to call the function.
	// This is default when Functions are provided.
	FunctionCallAuto = "auto"

	// FunctionCallNone indicates the mode should not call any functions.
	// This is the default when no Functions are provided.
	FunctionCallNone = "none"
)

// Schema defines a schema for a JSON object.
//
// See https://json-schema.org/understanding-json-schema/
type Schema struct {
	Type        string            `json:"type"`
	Description string            `json:"description,omitempty"`
	Properties  map[string]Schema `json:"properties,omitempty"`
	Required    []string          `json:"required,omitempty"`
}

// Function is a function the model may generate JSON inputs for
type Function struct {
	Name        string `json:"name"`
	Description string `json:"description,omitempty"`
	Parameters  Schema `json:"parameters"`
}

// FunctionCall is the name and arguments of a function that should be called,
// as generated by the model.
type FunctionCall struct {
	Name      string `json:"name"`
	Arguments string `json:"arguments"`
}
